[package]
name = "tikcopy"
version = "0.1.0"
edition = "2024"

[dependencies]
arboard = "3.2"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0"
atty = "0.2"
colored = "2.1"